name: homenest_vendor
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.2
  image_picker: ^1.2.0
  url_launcher: ^6.3.2
  toastification: ^3.0.3
  get: ^4.7.2
  get_storage: ^2.1.1
  connectivity_plus: ^7.0.0
  dio: ^5.9.0
  firebase_core: ^4.1.1
  firebase_messaging: ^16.0.2
  flutter_local_notifications: ^19.4.2
  intl: ^0.20.2
  device_info_plus: ^12.1.0
  flutter_keyboard_visibility: ^6.0.0
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  share_plus: ^12.0.0
  in_app_review: ^2.0.11
  new_version_plus: ^0.1.1
  mime: ^2.0.0
  file_picker: ^10.3.3
  audioplayers: ^6.5.1
  vibration: ^3.1.4
  socket_io_client: ^3.1.2
  flutter_feather_icons: ^2.0.0+1
  shimmer: ^3.0.0
  map_launcher: ^4.4.2
  carousel_slider: ^5.1.1
  flutter_offline: ^6.0.0
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/